"""
ReAct Pattern Implementation.

Implements the Reasoning + Acting loop where agents alternate between
thinking (reasoning) and acting (executing tools). Provides a structured
approach to agent decision-making with clear observation-action-reflection cycles.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
from enum import Enum
import structlog

logger = structlog.get_logger(__name__)


class AgentState(Enum):
    """Enumeration of agent states during reasoning and acting."""
    THINKING = "thinking"
    ACTING = "acting"
    OBSERVING = "observing"
    DONE = "done"


@dataclass
class Thought:
    """Represents a single reasoning step."""
    content: str
    timestamp: float = field(default_factory=lambda: __import__('time').time())


@dataclass
class Action:
    """Represents a single action to execute."""
    tool: str
    input: Dict[str, Any]
    timestamp: float = field(default_factory=lambda: __import__('time').time())


@dataclass
class Observation:
    """Represents the result of an action."""
    content: Any
    timestamp: float = field(default_factory=lambda: __import__('time').time())


class ReActAgent:
    """
    ReAct Agent implementing the Reasoning + Acting loop.

    The agent cycles through:
    1. Think: Generate reasoning about the task
    2. Act: Execute a tool based on reasoning
    3. Observe: Collect and analyze the result
    4. Reflect: Update internal state and continue or terminate
    """

    def __init__(
        self,
        model: str = "gpt-4",
        tool_gateway: Optional[Any] = None,
        max_iterations: int = 10,
        temperature: float = 0.7,
    ):
        """
        Initialize the ReAct Agent.

        Args:
            model: LLM model identifier (e.g., 'gpt-4', 'claude-3-opus')
            tool_gateway: ToolGateway instance for tool execution
            max_iterations: Maximum reasoning-action cycles
            temperature: LLM temperature for reasoning diversity
        """
        self.model = model
        self.tool_gateway = tool_gateway
        self.max_iterations = max_iterations
        self.temperature = temperature

        self.state = AgentState.THINKING
        self.iteration = 0
        self.thoughts: List[Thought] = []
        self.actions: List[Action] = []
        self.observations: List[Observation] = []
        self.final_answer: Optional[str] = None

        logger.info(
            "react_agent_initialized",
            model=model,
            max_iterations=max_iterations,
        )

    def think(self) -> str:
        """
        Generate reasoning about the current task and state.

        Returns:
            The reasoning/thought content generated by the LLM
        """
        context = self._build_context()

        # In production, this would call the LLM API
        # For now, we provide a structured placeholder
        thought_content = self._generate_thought(context)

        thought = Thought(content=thought_content)
        self.thoughts.append(thought)

        logger.info("agent_thought_generated", iteration=self.iteration)
        return thought_content

    def act(self, action_description: str) -> Any:
        """
        Execute a tool based on the action description.

        Args:
            action_description: Description of the action to take

        Returns:
            The result of the tool execution
        """
        action = self._parse_action(action_description)
        self.actions.append(action)

        if self.tool_gateway is None:
            logger.warning("tool_gateway_not_configured")
            return f"Would execute: {action.tool} with {action.input}"

        try:
            result = self.tool_gateway.execute_tool(action.tool, action.input)
            logger.info(
                "tool_executed_successfully",
                tool=action.tool,
                iteration=self.iteration,
            )
            return result
        except Exception as e:
            logger.error(
                "tool_execution_failed",
                tool=action.tool,
                error=str(e),
                iteration=self.iteration,
            )
            raise

    def observe(self, result: Any) -> None:
        """
        Process and record the result of an action.

        Args:
            result: The observation/result from tool execution
        """
        observation = Observation(content=result)
        self.observations.append(observation)

        logger.info(
            "observation_recorded",
            iteration=self.iteration,
            observation_type=type(result).__name__,
        )

    def run(self, task: str) -> str:
        """
        Execute the ReAct loop for a given task.

        Args:
            task: The task description or question for the agent

        Returns:
            The final answer or response
        """
        logger.info("react_agent_started", task=task)
        self.task = task
        self.iteration = 0

        while self.iteration < self.max_iterations:
            self.state = AgentState.THINKING
            thought = self.think()

            # Check if agent wants to finish
            if self._should_finish(thought):
                self.final_answer = self._extract_final_answer(thought)
                self.state = AgentState.DONE
                logger.info(
                    "react_agent_completed",
                    iterations=self.iteration,
                    answer_length=len(self.final_answer or ""),
                )
                return self.final_answer or "Task completed"

            self.state = AgentState.ACTING
            action_description = self._extract_action(thought)

            if not action_description:
                self.iteration += 1
                continue

            try:
                result = self.act(action_description)
                self.state = AgentState.OBSERVING
                self.observe(result)
            except Exception as e:
                logger.error("action_execution_error", error=str(e))
                self.observe(f"Error: {str(e)}")

            self.iteration += 1

        self.state = AgentState.DONE
        logger.warning(
            "react_agent_max_iterations_reached",
            max_iterations=self.max_iterations,
        )
        return self._generate_final_answer()

    def _build_context(self) -> str:
        """Build context string from thoughts, actions, and observations."""
        context_parts = [f"Task: {self.task}"]

        for i, (thought, action, obs) in enumerate(
            zip(self.thoughts, self.actions, self.observations)
        ):
            context_parts.append(f"Thought {i+1}: {thought.content}")
            context_parts.append(f"Action {i+1}: {action.tool}")
            context_parts.append(f"Observation {i+1}: {obs.content}")

        return "\n".join(context_parts)

    def _generate_thought(self, context: str) -> str:
        """Generate reasoning step. Placeholder for LLM call."""
        return f"Let me think about how to solve: {self.task}"

    def _extract_action(self, thought: str) -> Optional[str]:
        """Extract action from thought. Placeholder implementation."""
        if "would" in thought.lower() or "should" in thought.lower():
            return "analyze"
        return None

    def _should_finish(self, thought: str) -> bool:
        """Determine if agent should finish reasoning."""
        finish_words = ["finally", "therefore", "answer is", "conclusion"]
        return any(word in thought.lower() for word in finish_words)

    def _extract_final_answer(self, thought: str) -> str:
        """Extract final answer from thought."""
        return thought.split("answer is")[-1].strip() if "answer is" in thought else thought

    def _parse_action(self, action_description: str) -> Action:
        """Parse action description into Action object."""
        parts = action_description.split(":")
        tool = parts[0].strip() if len(parts) > 0 else "unknown"
        input_data = {"description": action_description}
        return Action(tool=tool, input=input_data)

    def _generate_final_answer(self) -> str:
        """Generate final answer from conversation history."""
        if self.final_answer:
            return self.final_answer
        if self.observations:
            return str(self.observations[-1].content)
        return "Unable to generate answer"

    def get_history(self) -> Dict[str, Any]:
        """Retrieve the complete conversation history."""
        return {
            "task": self.task,
            "iterations": self.iteration,
            "thoughts": [t.content for t in self.thoughts],
            "actions": [(a.tool, a.input) for a in self.actions],
            "observations": [o.content for o in self.observations],
            "final_answer": self.final_answer,
        }
